name: Build project with Maven
on:
  pull_request:
  schedule:
  - cron: '2 2 * * 1' # run nightly master builds every monday 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Java setup
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      run: mvn -B clean verify com.mycila:license-maven-plugin:check -Dfmt.skip -Denforcer.skip
